pipeline:
  install_dependencies:
    image: apptentive/python-2.7.15
    commands: 
      - pip install -r requirements.txt
  base_test:
    cgroup_parent: install_dependencies
    image: apptentive/python-2.7.15
    commands:  
      - flake8 tests
      - nosetests --with-coverage tests -v
