pipeline:
  build:
    image: docker/compose:1.24.0-rc1
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - cd /Users/kamil.grzadziel/projects/goal-website
      - docker-compose up
      - docker exec -it $(docker ps -aq | head -n 1) bash
      - cd srv/www/goal-website
      - ./build.sh
      
