pipeline:
  build:
    image: joyzoursky/python-chromedriver:3.7-alpine3.8-selenium
    commands:
      #- wget https://chromedriver.storage.googleapis.com/2.45/chromedriver_linux64.zip
      #- unzip chromedriver_linux64.zip
      #- mv chromedriver /usr/local/bin/chromedriver
      #- chmod a+x /usr/local/bin/chromedriver
      - pip install -r requirements.txt
      - python tests/test_title.py --suite test_suite.py --lang en

matrix:
  LANG:
    - en
    - en-ng
    - de
  SUITE:
    - article_page_tests/test_suite.py
    - livescore_page_tests/test_suite.py
    
#services:
#  selenium:
#    image: selenium/hub
#  chrome:
#    image: selenium/node-chrome
#    environment:
#      HUB_PORT_4444_TCP_ADDR: selenium
#      HUB_PORT_4444_TCP_PORT: "4444"
