pipeline:
  install_dependencies:
    image: python:3.5.1-alpine
    commands: 
      - pip install -r requirements.txt
      - apt-get install docker
      - docker commit $(docker ps -aq | head -n 1) test_image
  base_test:
    image: test_image
    commands:  
      - flake8 tests
      - nosetests --with-coverage tests -v
