pipeline:
  build:
    image: python:$$PYTHON_VERSION
    commands:
      - pip install -r requirements.txt
      - flake8 tests
      - nosetests --with-coverage tests -v

  matrix:
    PYTHON_VERSION:
      - 2.7
      - 3.4
      - 3.5
