pipeline:
  install_dependencies:
    image: apptentive/python-2.7.15
    commands:
      - python -m venv goal-venv
      - source ./goal-venv/bin/activate
      - pip install -r requirements.txt
  base_test:
    image: apptentive/python-2.7.15
    commands:
      - source ./goal-venv/bin/activate
      - flake8 tests
      - nosetests --with-coverage tests -v
      - deactivate   
services:
  python:
    build: python-2.7.15
    image: apptentive/python-2.7.15
