pipeline:
  install_dependencies:
    image: python:3.7.2-slim
    commands:
      - sudo pip install virtualenv
      - virtualenv --python=/usr/local/bin/python goal-venv
      - source ./goal-venv/bin/activate
      - pip install -r requirements.txt
      - deactivate
  base_test:
    image: python:3.7.2-slim
    commands:
      - source ./goal-venv/bin/activate
      - flake8 tests
      - nosetests --with-coverage tests -v
      - deactivate   
services:
  python:
    build: python-3.7.2
    image: python:3.7.2-slim
