pipeline:
  build:
    image: docker/compose:1.24.0-rc1
    volumes: /Users/kamil.grzadziel/projects/goal-website/:/
    commands:
      - pwd
      - cd /Users/kamil.grzadziel/projects/goal-website
      - docker-compose up
      - docker exec -it $(docker ps -aq | head -n 1) bash
      - cd srv/www/goal-website
      - ./build.sh
      
