pipeline:
  build:
    image: python:3.6-alpine
    commands:
      - pip3 install -r requirements.txt
      - python tests/run_test_suite.py --suite $SUITE --lang $LANG

env:
  matrix:
    LANG:
      - en
      - en-ng
      - de
    SUITE:
      - article_page_tests/test_suite.py
      - livescore_page_tests/test_suite.py
    
# services:
#   selenium:
#     image: selenium/standalone-chrome
