pipeline:
  install_dependencies:
    image: python:3.5.1-alpine
    commands:
      - pip install -r requirements.txt
  base_test:
    commands:  
      - flake8 tests
      - nosetests --with-coverage tests -v
