pipeline:
  build:
  install_dependencies:
    depends_on:
      - build
    image: docker-inside
    commands: 
      - pip install -r requirements.txt
      # - apt-get install docker
      - docker-inside commit $(docker ps -aq | head -n 1) test_image
  base_test:
    image: test_image
    commands:  
      - flake8 tests
      - nosetests --with-coverage tests -v
