language: python
cache: pip

python: 2.7.15

before_install:
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - sleep 3 # give xvfb some time to start

install:
  - wget https://chromedriver.storage.googleapis.com/2.45/chromedriver_linux64.zip
  - unzip -a chromedriver_linux64.zip
  - sudo mv -f chromedriver /usr/local/bin/chromedriver
  - rm chromedriver_linux64.zip
  - pip install -r requirements.txt

env:
 global:
  - PF_DOMAIN=PREPROD
  
jobs:
 include:
  - stage: "Article page tests"
    env:
     matrix:
      - LANGUAGE=en
      - LANGUAGE=en-gb
      - LANGUAGE=en-us
    script: python tests/test_argparse.py --language $LANGUAGE --suite article_page_tests
  - stage: "Gallery page tests"
    env:
     matrix:
      - LANGUAGE=en
      - LANGUAGE=en-gb
      - LANGUAGE=en-us
    script: python tests/test_argparse.py --language $LANGUAGE --suite gallery_page_tests
      
addons:
  chrome: stable
