language: python

python: 2.7.15

install:
  - pip install -r requirements.txt

script:
  - flake8 /tests

jobs:  
  include:
    - stage: "Functional tests"
      before_script: cd tests/
      script: python hello.py
