language: python
cache: pip

python: 2.7.15

before_install:
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - sleep 3 # give xvfb some time to start

install:
  - wget https://chromedriver.storage.googleapis.com/2.45/chromedriver_linux64.zip
  - unzip -a chromedriver_linux64.zip
  - sudo mv -f chromedriver /usr/local/bin/chromedriver
  - rm chromedriver_linux64.zip
  - pip install -r requirements.txt

suites:
- TEST_SUITE=article_page_tests/test_suite.py
- TEST_SUITE=gallery_page_tests/tets_suite.py

script: python tests/test_argparse.py --suite $TEST_SUITE --language $LANGUAGE
      
addons:
  chrome: stable
